version: 2.1

# orbs:
#   codecov: codecov/codecov@1.1.3
#   shellcheck: circleci/shellcheck@1.2.0
#   windows: circleci/windows@2.2.0

executors:
  go:
    docker:
      - image: circleci/golang:1.17
    environment:
      CGO_ENABLED: 0
commands:
  build-docker-image:
    steps:
      - run:
          name: Build Latest Docker Image
          command: |
            docker build -t circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM .
            docker run --rm circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM circleci update check
  deploy-save-cache-workspace-and-artifacts:
    steps:
      - save_cache:
          key: v4-goreleaser-{{ checksum "~/goreleaser_amd64.deb" }}
          paths: [~/goreleaser_amd64.deb]
      - persist_to_workspace:
          root: .
          paths:
            - "dist"
      - store_artifacts:
          path: ./dist
          destination: dist
  gomod:
    steps:
      - restore_cache:
          keys: ["v2-gomod-{{ arch }}-"]
      - run:
          name: Download go module dependencies
          command: go mod download
      - save_cache:
          key: v2-gomod-{{ arch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod # Linux

jobs:
  go-build:
    executor: go
    steps:
      - checkout
      - gomod
      - run: make
      - persist_to_workspace:
          root: .
          paths:
            - "build"
  docker-build:
    docker:
      - image: cimg/base:2022.03
    environment:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/kesin11/circleci-cli-sandbox
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: docker version
      - run:
          name: Simple docker build
          command: docker image build --progress=plain -t $IMAGE:latest -f Dockerfile .
  docker-build-cache-mount:
    docker:
      - image: cimg/base:2022.03
    environment:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/kesin11/circleci-cli-sandbox
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: docker version
      - run:
          name: Docker build with cache mount
          command: docker image build --progress=plain -t $IMAGE:latest -f Dockerfile_cache_mount .
  # deploy:
  #   executor: go
  #   steps:
  #     - checkout
  #     - gomod
  #     - setup_remote_docker:
  #         docker_layer_caching: true
  #     - run:
  #         name: Docker Login
  #         command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
  #     - build-docker-image
  #     - run:
  #         name: Deploy Docker Image
  #         command: |
  #           docker push     circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM
  #           docker tag      circleci/circleci-cli:0.1.$CIRCLE_BUILD_NUM circleci/circleci-cli:latest
  #           docker push     circleci/circleci-cli:latest
  #     - deploy-save-cache-workspace-and-artifacts
workflows:
  ci:
    jobs:
      - docker-build
      - docker-build-cache-mount
      # - deploy:
      #     filters:
      #       branches:
      #         only: master
