version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.17
    environment:
      CGO_ENABLED: 0
      GOCACHE: "/tmp/go/cache"
  cimg-docker:
    docker:
      - image: cimg/base:2022.03
    environment:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/kesin11/circleci-cli-sandbox

commands:
  gomod:
    steps:
      - restore_cache:
          keys: ["v2-gomod-{{ arch }}-"]
      - run:
          name: Download go module dependencies
          command: go mod download
      - save_cache:
          key: v2-gomod-{{ arch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod # Linux
  setup-docker:
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - run: docker version
  setup-buildx:
    steps:
      - run:
          name: Show docker info
          command: |
            docker version
            docker buildx version
            docker context inspect
      - run:
          name: Setup docker buildx
          command: |
            docker context create circleci
            docker buildx create --use circleci
            docker buildx ls
            docker context inspect circleci

jobs:
  docker-build:
    executor: cimg-docker
    resource_class: small
    steps:
      - checkout
      - setup-docker
      - run:
          name: Simple docker build
          command: docker image build --progress=plain -t $IMAGE:latest -f Dockerfile .
  docker-build-cache-mount:
    executor: cimg-docker
    resource_class: small
    steps:
      - checkout
      - setup-docker
      - run:
          name: Docker build with cache mount
          command: docker image build --progress=plain -t $IMAGE:latest -f Dockerfile_cache_mount .
  docker-build-registry-cache:
    executor: cimg-docker
    resource_class: small
    steps:
      - checkout
      - setup-docker
      - setup-buildx
      - run: echo $GITHUB_CR_PAT | docker login ghcr.io -u kesin11 --password-stdin
      - run:
          name: Docker build with registry cache
          command: |
            docker buildx build --progress=plain -f Dockerfile \
              --cache-to=type=registry,mode=max,ref=$IMAGE:invalid_cache \
              --cache-from=type=registry,ref=$IMAGE:cache \
              -t $IMAGE:latest .
  docker-build-local-cache:
    executor: cimg-docker
    resource_class: small
    steps:
      - checkout
      - setup-docker
      - setup-buildx
      - restore_cache:
          keys: 
            - v2-docker-cache-{{ arch }}-{{ .Branch }}-
            - v2-docker-cache-{{ arch }}-
      - run:
          name: Docker build with local cache
          command: |
            docker buildx build --progress=plain -f Dockerfile \
              --cache-to=type=local,mode=max,dest=/tmp/docker_cache_invalid \
              --cache-from=type=local,src=/tmp/docker_cache \
              -t $IMAGE:latest .
      - save_cache:
          key: v2-docker-cache-{{ arch }}-{{ .Branch }}-{{ checksum "/tmp/docker_cache_invalid/index.json" }}
          paths:
            - /tmp/docker_cache
            - /tmp/docker_cache_invalid
  docker-build-copy-bin:
    executor: go
    environment:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/kesin11/circleci-cli-sandbox
    resource_class: small
    steps:
      - checkout
      - gomod
      - restore_cache:
          keys:
            - build-cache-{{ .Branch }}-
            - build-cache-
      - run: make
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Revision }}-invalid
          paths:
              - /tmp/go/cache
      - setup-docker
      - run:
          name: Docker build only copy bin
          command: |
            rm -f .dockerignore
            docker image build -f Dockerfile_copy_bin \
              -t $IMAGE:copy_bin \
              .
workflows:
  ci:
    jobs:
      - docker-build
      - docker-build-cache-mount
      - docker-build-registry-cache
      - docker-build-local-cache
      - docker-build-copy-bin
